{{- with index .Values "gpp-burgerportaal" "settings"  }}
    {{- if and ((.elasticsearch).username) (.elasticsearch.password) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default "elastic-burgerportaal-user" .elasticsearch.secretName }}
  labels:
      {{- with $ }}
      {{- include "gpp-stack.labels" . | nindent 4 }}
      {{- end }}
stringData:
  username: {{ .elasticsearch.username }}
  password: {{ .elasticsearch.password }}
  roles: {{ default "viewer" .elasticsearch.role }}
    {{- end }}
{{- end }}
---
{{- with index .Values "gpp-publicatiebank" "settings"  }}
  {{- if and ((.elasticsearch).username) (.elasticsearch.password) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default "elastic-publicatiebank-user" .elasticsearch.secretName }}
  labels:
    {{- with $ }}
    {{- include "gpp-stack.labels" . | nindent 4 }}
    {{- end }}
stringData:
  username: {{ .elasticsearch.username }}
  password: {{ .elasticsearch.password }}
  roles: {{ default "superuser" .elasticsearch.role }}
  {{- end }}
{{- end }}
